ACGS guidelines URL fix
eastgenomics/eggd_pandora pull request #7
Opened 2024-06-27 13:58 UTC by kjwinfield

- Change add_nuh_id function to no longer submit on behalf of NUH, as the API key allows NUH to be primary submitter
- Retool and rename add_nuh_id to add_lab_specific_guidelines. This function now adds the correct link to the ACGS guidelines that are specific to the submitting lab i.e. CUH or NUH
- Add tests for new add_lab_specific_guidelines function
- Update app version from v2.0.1 → v2.0.2
- Change get_clinvar_accession.py script so that it exists if clinvar_testing is true; as the clinvar test endpoint does not produce accession IDs, so trying to extract them is a waste of time.

2024-06-27 13:58 UTC, pep8speaks commented
Hello @kjwinfield! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`resources/home/dnanexus/get_clinvar_accession.py`](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/get_clinvar_accession.py):

> [Line 180:57](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/get_clinvar_accession.py#L180): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`resources/home/dnanexus/pull_from_csv.py`](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/pull_from_csv.py):

> [Line 164:9](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/pull_from_csv.py#L164): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 165:9](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/pull_from_csv.py#L165): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 170:9](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/pull_from_csv.py#L170): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 171:9](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/pull_from_csv.py#L171): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

* In the file [`resources/home/dnanexus/tests/test_pandora.py`](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/tests/test_pandora.py):

> [Line 429:32](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/tests/test_pandora.py#L429): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 440:32](https://github.com/eastgenomics/eggd_pandora/blob/498c49293aec8148f4a9030875d8f2ffc858dcf8/resources/home/dnanexus/tests/test_pandora.py#L440): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'

2024-06-28 10:17 UTC, wintun12 approved these changes

2024-06-28 11:27 UTC, pofuoku requested changes
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7)* status: 3 of 5 files reviewed, 4 unresolved discussions (waiting on @kjwinfield)

___
*[`dxapp.json` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0TV11g3nQ4vOcVR7q_:-O0TV11g3nQ4vOcVR7qa:bi4p2iz) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/dxapp.json#L5)):*
> ```JSON
>     "title": "eggd_pandora",
>     "summary": "Takes patient and variant information and shares with online databases",
>     "whatsNew": "* 2.0.0 Updated to take data from a csv file and input to ClinVar\n * 2.0.1 bugfix for incorrect field name\n * 2.0.2 add NUH ACGS guidelines link",
> ```

The whatsNew will become unreadable as more versions are added. I find it difficult to read. Since this is just a metadata and doesn't affect functionallity of app, could the whatsNew be in form of a key, value pair like we do in changelog of config file. something like this should be more readbale:

"whatsNew": {
                         "v2.0.0: "Updated to take data from a csv file and input to ClinVar",
                         "v2.0.1" :  "bugfix for incorrect field name",
                         "v2.0.2":   "add NUH ACGS guidelines link" 
},

This is much cleaner, but if you have other reasons, could you please clarify?



_Code quote:_
```JSON
"whatsNew": "* 2.0.0 Updated to take data from a csv file and input to ClinVar\n * 2.0.1 bugfix for incorrect field name\n * 2.0.2 add NUH ACGS guidelines link",
```
___
*[`resources/home/dnanexus/pull_from_csv.py` line 159 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0TXOMSB8tbyWygTPD1:-O0TXOMT9CLRE2CbhWPp:b-dpieb5) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/resources/home/dnanexus/pull_from_csv.py#L159)):*
> ```Python
>     Outputs:
>         clinvar_dict (dict): dictionary of info to submit to clinvar, edited
>         to add url to assertion criteria, and behalf org ID for NUH
> ```

Please clarify if the behalfOrgID is part of the assertion criteria. Because you removed the behalfOrgID key from clinvar_dict and replaced with assertionCriteria. Was that intentional? Or do you want to keep both keys like the docstring suggests, if not modify the docstring to be very clear.



_Code quote:_
```Python
        clinvar_dict (dict): dictionary of info to submit to clinvar, edited
        to add url to assertion criteria, and behalf org ID for NUH
```
___
*[`resources/home/dnanexus/tests/test_pandora.py` line 427 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0TZcpCE-pZYMzNunoS:-O0TZcpCE-pZYMzNunoT:bngzas8) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/resources/home/dnanexus/tests/test_pandora.py#L427)):*
> ```Python
>         """
>         Test that behalfOrgID field is added if organisation is NUH
>         """
> ```

It seems you forgot to modify the test docstrings. Is the assertionCriteria field synonymous with behalforg field?



_Code quote:_
```Python
    def test_nuh_org_url_added(self):
        """
        Test that behalfOrgID field is added if organisation is NUH
        """
```
___
*[`resources/home/dnanexus/tests/test_pandora.py` line 438 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0T_QZU9IWfGvjOgrmH:-O0T_QZU9IWfGvjOgrmI:b-aa1myr) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/resources/home/dnanexus/tests/test_pandora.py#L438)):*
> ```Python
>         """
>         Test that clinvar_dict is not changed if organisation is CUH
>         """
> ```

Same as above. The docstring doesn't describe the test and contradicts the function name. Please clarify.



_Code quote:_
```Python
    def test_cuh_org_url_added(self):
        """
        Test that clinvar_dict is not changed if organisation is CUH
        """
```


<!-- Sent from Reviewable.io -->

2024-06-28 12:45 UTC, kjwinfield reviewed
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @pofuoku)

___
*[`dxapp.json` line 5 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0TV11g3nQ4vOcVR7q_:-O0TsCRS2OnOS6FFhrRp:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/dxapp.json#L5)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

The whatsNew will become unreadable as more versions are added. I find it difficult to read. Since this is just a metadata and doesn't affect functionallity of app, could the whatsNew be in form of a key, value pair like we do in changelog of config file. something like this should be more readbale:

"whatsNew": {
                         "v2.0.0: "Updated to take data from a csv file and input to ClinVar",
                         "v2.0.1" :  "bugfix for incorrect field name",
                         "v2.0.2":   "add NUH ACGS guidelines link" 
},

This is much cleaner, but if you have other reasons, could you please clarify?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/pull_from_csv.py` line 159 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0TXOMSB8tbyWygTPD1:-O0TsDK7D5be_gdbnuq7:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/resources/home/dnanexus/pull_from_csv.py#L159)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Please clarify if the behalfOrgID is part of the assertion criteria. Because you removed the behalfOrgID key from clinvar_dict and replaced with assertionCriteria. Was that intentional? Or do you want to keep both keys like the docstring suggests, if not modify the docstring to be very clear.
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/tests/test_pandora.py` line 427 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0TZcpCE-pZYMzNunoS:-O0TsDlf03CQIsYfKvSb:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/resources/home/dnanexus/tests/test_pandora.py#L427)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

It seems you forgot to modify the test docstrings. Is the assertionCriteria field synonymous with behalforg field?
</blockquote></details>

Done.
___
*[`resources/home/dnanexus/tests/test_pandora.py` line 438 at r2](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7#-O0T_QZU9IWfGvjOgrmH:-O0TsEAq6i4vOW1vXjhw:b-896fix) ([raw file](https://github.com/eastgenomics/eggd_pandora/blob/9f860a1ffd1214e5b3932951ad60600f242dfca6/resources/home/dnanexus/tests/test_pandora.py#L438)):*
<details><summary><i>Previously, pofuoku (Prince Ofuoku) wrote…</i></summary><blockquote>

Same as above. The docstring doesn't describe the test and contradicts the function name. Please clarify.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2024-06-28 15:23 UTC, pofuoku approved these changes
> Reviewed 2 of 2 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_pandora/7)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @kjwinfield)



<!-- Sent from Reviewable.io -->

2024-07-01 10:51 UTC, merged